<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<title>Promise</title>
	</head>

	<body></body>
	<script>
		function loadScript(src, callback) {
			let script = document.createElement("script");
			script.src = src;

			script.onload = () => callback(null, script);
			script.onerror = () =>
				callback(new Error(`Script load error for ${src}`));

			document.head.append(script);
		}

		loadScript("./Promise.js", (error, script) => {
			if (!error) {
				g();
				loadScript("./Promise.js", (error, script) => {
					if (error) {
						console.log(error);
					}
				});
			}
		});
		//弊端 : 当有多个需要加载时会产生 “回调地狱”或“厄运金字塔”。
		//=========================================================================================
		//Promise

		/*
* 传递给 new Promise 的函数被称为 executor,创建是自动运行。
* resolve 和 reject 是由 JavaScript 自身提供的回调
* 当 executor 有了结果应该调用其中一个回调函数,只能调一个,多余将被忽略
	resolve(value) — 如果任务成功完成并带有结果 value。
	reject(error) — 如果出现了 error，error 即为 error 对象。
*/

		//生产者代码
		let promise = new Promise(function (resolve, reject) {
			setTimeout(() => resolve("成功"), 1000);
			//setTimeout(() => resolve('成功'), 1000);
		});
		console.log(promise);
		/*
* 创建初始属性
	State  ： pending      ==>   resolve('val')  ==>   fulfilled    or==> reject('val')  ==>  rejected
	Result ： undefined								   val                                    error
*/

		//消费者代码 then，catch，finally
		promise.then(
			(res) => {
				console.log(res);
			}, //调用resolve
			(err) => {
				console.log(err);
			} //调用reject
		);

		//如果只要err结果
		//Promise 的执行者（executor）和前面的 promise 的处理程序（handler）中如果有报错
		promise.catch((err) => {}); //多次.then不管那一次报错都会走最后一个catch
		promise.then(null, (err) => {
			console.log("dddddd");
		});

		//无论成功失败、但它没有参数
		promise.finally(() => console.log("data"));

		//链式操作
		new Promise(function (resolve, reject) {
			setTimeout(() => resolve(1), 3000); // (*)
		})
			.then(function (result) {
				// (**)

				console.log(result); // 1
				return result * 2;
			})
			.then(function (result) {
				// (***)
				/*
                    手动终止后面的.then，直接条catch
                    throw new Error('手动终止')
                */
				console.log(result); // 2
				return new Promise((resolve) => {
					setTimeout(() => resolve(result * 2), 3000);
				});
			})
			.then(function (result) {
				console.log(result); // 4
				return result * 2;
			});

		// Promise API
		//[1,2,3] 并行执行,全部成功才能到then1,否则then2或.catch
		Promise.all([
			new Promise((resolve) => setTimeout(() => resolve(1), 3000)), // 1
			new Promise((resolve) => setTimeout(() => resolve(2), 2000)), // 2
			new Promise((resolve, reject) => setTimeout(() => reject(3), 1000)), // 3
		]).then(
			(res) => console.log(res),
			(err) => console.log("err" + err)
		);

		//即使有reject 也会得到信息
		Promise.allSettled([
			new Promise((resolve) => setTimeout(() => resolve(1), 3000)), // 1
			new Promise((resolve) => setTimeout(() => resolve(2), 2000)), // 2
			new Promise((resolve, reject) =>
				setTimeout(() => reject(300), 1000)
			), // 3
		]).then(
			(res) => console.log(res),
			(err) => console.log("err" + err)
		);

		//race 获取执行最快的结果
		Promise.race([
			new Promise((resolve) => setTimeout(() => resolve(1), 1000)), // 1
			new Promise((resolve) => setTimeout(() => resolve(2), 1000)), // 2
			new Promise((resolve, reject) =>
				setTimeout(() => reject(300), 1000)
			), // 3
		]).then(
			(res) => console.log(res),
			(err) => console.log("err" + err)
		);

		//Promise.resolve/reject 很少用

		// =====================================================================================
		// async/await同时存在 async:function/await必须在这个function内使用
		// async声明的函数的返回本质上是返回一个Promise。
		// async 后必须跟function  //必须是这个格式函数
		// await 等待直到 promise 完成（settle）并返回结果
		// 相比于 promise.then，它只是获取 promise 的结果的一个更优雅的语法，同时也更易于读写
		// .......
		// async 异步方法，外面调用 doIt2() 时不会阻塞，会继续执行后面的代码
        // async 内部的await,会等待 函数内部 每一个异步操作返回结果在继续执行函数内部的流程

		const demo = async () => {
			let result = await new Promise((resolve, reject) => {
				console.log("await内部先");
				setTimeout(() => resolve("2000++"), 2000);
			});
			console.log(
				"我由于上面的程序还没执行完，先不执行“等待一会”" + result
			);
			return result;
		};
		demo().then((result) => {
			console.log("输出", result);
		});
		console.log('不等待 demo 结束')

		//直接用Promise 与 async/await

		function takeLongTime(n) {
			return new Promise((resolve) => {
				setTimeout(() => resolve(n + 2000), n);
			});
		}

		function step1(n) {
			console.log(`step1 with ${n}`);
			return takeLongTime(n);
		}

		function step2(n) {
			console.log(`step2 with ${n}`);
			return takeLongTime(n);
		}

		function step3(n) {
			console.log(`step3 with ${n}`);
			return takeLongTime(n);
		}

		function doIt() {
			console.time("doIt");
			const time1 = 3000;
			step1(time1)
				.then((time2) => step2(time2))
				.then((time3) => step3(time3))
				.then((result) => {
					console.log(`result is ${result}`);
				});
		}
		//doIt();

		async function doIt2() {
			console.time("doIt");
			const time1 = 3000;
			const time2 = await step1(time1); //在这里step1没执行完成是不好走下一步的
			const time3 = await step2(time2);
			const result = await step3(time3);
			await new Promise((resolve) => {
				setTimeout(() => {
					console.log("先执行");
					resolve();
				}, 5000);
			});
			console.log("后执行");
			console.log(`result is ${result}`);
		}
		//doIt2();
		//console.log('doIt2 是异步行数，所有这里先走，不需要等待 doIt2 内部结束')
	</script>
</html>
